### ISSUE TITLE
Expose a filepicker_field_tag method

### ISSUE THREAD

**Issue by danmichaelson** [Ink/filepicker-rails#102]
The ```f.filepicker_field``` method requires a a valid object attribute. Sometimes you want to do an upload and handle it entirely through the ```onchange``` event. In my case it's because I am trying to instantiate nested forms after a multi-file upload, one nested form for each file. But I'd still like to use all the config options I've set. A basic ```filepicker_field_tag``` method would support this, where you can specify any arbitrary attribute name for the input field.

**Comment by kwent** [comment]
+ 1

**Comment by maurogeorge** [comment]
Closed via #120
