### ISSUE TITLE
Issue with options

### ISSUE THREAD

**Issue by bbnnt** [Ink/filepicker-rails#114]
Getting into the service, options are cool
Thing is, I'm testing the implantation through rails

But 'multiple' & 'drag_text' options does not work   implemented this way : 

```<%= f.filepicker_field :file_url, dragdrop: true, services: %w( COMPUTER ), multiple: true, drag_text: "Ajouter...", container: "modal" %>```

Should it be done another way ? Is it restricted to another subscriptions level ?

**Comment by maurogeorge** [comment]
Closing, since no feedback was provided here.
