### ISSUE TITLE
How to require filepicker lib and how to write onchange callback and return file url?

### ISSUE THREAD

**Issue by Captain1** [Ink/filepicker-rails#118]
1 Upload works fine in but i want to return file url after submission and store to my Doc:filepicker_url column. Then display the doc in an iframe:
![image](https://cloud.githubusercontent.com/assets/4882809/6701631/75e3962c-cd17-11e4-95a3-7fe77ee37f72.png)

First question: How to require filepicker library in my docpicker.js file? I have put both the filepicker lib and my docpicker.js files before the end of body tag:
![image](https://cloud.githubusercontent.com/assets/4882809/6701868/6ec52484-cd1a-11e4-8c32-60df8b533dc4.png)
I also tried filepicker-node: https://www.npmjs.com/package/filepicker-node 
but received 'require' not defined when
![image](https://cloud.githubusercontent.com/assets/4882809/6701906/f4b2b5ca-cd1a-11e4-90fe-a44c74c3b399.png)

So how to correctly require the filepicker.js in Rails4.2?(I have nodejs installed both globally and in app(execjs gem installed)).

2 As mentioned in the document, any ideas on how to write onchange callback and extract event.fpfile.url and store into String 'filepicker_url' in my Doc Model? 
![image](https://cloud.githubusercontent.com/assets/4882809/6701785/7e76a76e-cd19-11e4-8de5-01622c1bce3b.png)

I use Rails for my school final project and i am new to javascript. Last semester teacher taught us angular, mongodb ,express, rails so I need time to absorb all these. Since is a stupid question please close this issue once i got the answer.

**Comment by Captain1** [comment]
![image](https://cloud.githubusercontent.com/assets/4882809/6701692/1e235e76-cd18-11e4-875e-0561aad8ca48.png)
So how on earth to correctly require the filepicker.js in Rails4.2?(I have nodejs installed both globally and in app(execjs gem installed)).

2 As mentioned in the document, any ideas on how to write onchange callback and extract event.fpfile.url and store into String 'filepicker_url' in my Doc Model? 
![image](https://cloud.githubusercontent.com/assets/4882809/6701785/7e76a76e-cd19-11e4-8de5-01622c1bce3b.png)

**Comment by maurogeorge** [comment]
To require the filepicker on rails 4.2 just use the `filepicker_js_include_tag`, as documented on [README](https://github.com/Ink/filepicker-rails).

Please use the StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
