### ISSUE TITLE
extension will be replaced if use :store_path option

### ISSUE THREAD

**Issue by chrisyeung1121** [Ink/filepicker-rails#121]
I believe it's a bug? or is it designed deliberately? the .png, .jpg, .jpeg will all be gone after using the :store_path option.

**Comment by maurogeorge** [comment]
@chrisyeung1121 The filepicker-rails gem is a thin wrapper around the javascript. The `:store_path` option simple add the `data-fp-store-path` to the input as you can [see here on the specs](https://github.com/Ink/filepicker-rails/blob/master/spec/support/shared_examples_for_filepicker_tags.rb#L87-L91).

At the [official filepicker documentation we have more content about the `data-fp-store-path`](https://www.filepicker.com/documentation/file_ingestion/widgets/pick).

This helps you @chrisyeung1121 ?

**Comment by maurogeorge** [comment]
Closing, since no feedback.
