### ISSUE TITLE
Use filepicker javascript library v2

### ISSUE THREAD

**Issue by lubaochuan** [Ink/filepicker-rails#122]
When I use this gem and I see in the generated HTML v1 of the javascript library:`<script src="//api.filepicker.io/v1/filepicker.js" type="text/javascript"></script>` 
Can we switch to v2, which includes new features such as crop UI?

**Comment by maurogeorge** [comment]
Good catch!

In the [filepicker documentation about the migration](https://www.filepicker.com/documentation/file_ingestion/javascript_api/migration?v=v2) we see that the V2 has no breaking changes, so we can add this new javascript link and release the 1.5.0, since we are [following semver](https://github.com/Ink/filepicker-rails#versioning) and this changes does not break any old api.

**Comment by lubaochuan** [comment]
Great! I look forward to release 1.5.0. Thanks.

**Comment by maurogeorge** [comment]
Hi @lubaochuan just to let you know that [I released the new version today](https://rubygems.org/gems/filepicker-rails). Check the full changes on the [CHANGELOG](https://github.com/Ink/filepicker-rails/blob/master/CHANGELOG.md#150-june-10-2015).

**Comment by lubaochuan** [comment]
Thanks. I tried to take advantage of the v2 UI using filepicker_field with
cropratio, mimetypes, and services as follows:
= f.filepicker_field :image, :button_text => t('edit.update_photo'),
    cropRatio: '4/4', mimetypes: ['image/*'],  services: ['CONVERT',
'COMPUTER']

It doesn't work and give the following error:
[uuid=81B0E1AE6D8442B4] Error: the service undefined couldn't be found or
does not support the given mimetype(s): [u'image/*']

What am I doing wrong? Please advise.

I am also trying to use the policy+signature to protect my files. What
possible harm a user, who has my api key, policy, and signature, do?


Thanks,
Baochuan

**Comment by krystiangw** [comment]
Hi @lubaochuan. 
Error:
[uuid=81B0E1AE6D8442B4] Error: the service undefined couldn't be found or
does not support the given mimetype(s): [u'image/*']

may indicate that you are still using filepicker.js v1 -  it doesn't recognize 'CONVERT' service.

How does it works with any other services?

**Comment by lubaochuan** [comment]
I checked the generated HTML and see the following:
<script src="//api.filepicker.io/v2/filepicker.js"
type="text/javascript"></script>

The javascript library works fine so I guess I am not using the methods for
rails correctly. Could you provide me a code example that uses
filepicker_field with options such as cropratio, services, and mimetypes?

Thanks,
Baochuan

**Comment by maurogeorge** [comment]
@lubaochuan I recommend you try to use the HTML directly like [docummented here](https://www.filepicker.com/documentation/file_ingestion/widgets/pick?v=v2) and see the output and test the behavior. Later you can try the same output with the gem.

**Comment by lubaochuan** [comment]
Thanks! I am at a conference right now. When I get back I will give it a
try and get back to you.

Baochuan

**Comment by omidn** [comment]
anyone made any progress on this?
