### ISSUE TITLE
Change to API V2 breaks SemVer

### ISSUE THREAD

**Issue by monkbroc** [Ink/filepicker-rails#125]
I would kindly request that you bump your main version to 2.0.0 since you are now including a different Javascript file and showing a completely different user interface dialog.

Your readme states that the gem Filepicker::Rails follows Semantic Versioning.

I updated the gems in my application and saw only a minor version bump on the Filepicker gem. I went ahead and deployed, and now file uploads are broken. It's my fault for not covering this in my tests, but I would have checked closer with a new major version of the gem.

Please take SemVer seriously and increase the major version when doing something like changing the entire user interface and API version used.

I would also encourage you to release 1.6.0 with the same content as 1.4.0, so that people who want to stay with the API V1 and the old dialog for the time being can stick `gem "filepicker-rails", "~> 1.0"` in their `Gemfile`. Just leave 1.5.x alone (don't pull it from RubyGems). It's the best course of action to avoid surprising people who update to the next minor version of the gem.

Thanks. :heart:

**Comment by maurogeorge** [comment]
Hi @monkbroc thanks for your comment.

[Since the migration of JavaScript from V1 to V2 has no breaking changes](https://www.filepicker.com/documentation/file_ingestion/javascript_api/migration?v=v2) was decided this was a [MINOR(version when you add functionality in a backwards-compatible manner)](https://github.com/Ink/filepicker-rails/blob/master/CHANGELOG.md#140-may-7-2015) in filepicker-rails.

> I went ahead and deployed, and now file uploads are broken

What exactly is broken? As said before the JavaScript has no breaking changes and  as you can see [here](https://github.com/Ink/filepicker-rails/blob/master/CHANGELOG.md#150-june-10-2015) none of the public API of filepicker-rails have changed.

Thanks

**Comment by monkbroc** [comment]
Thanks for the response @maurogeorge.

I didn't check exactly what was broken and just reverted to the previous gem version on the production server. But the principle of least surprise should apply here. Somebody at Filepicker thought the changes to the API were significant enough to warrant a new major version and I think the same applies to this gem.

I'd argue that the user-facing UI is part of the public API of the Filepicker gem and a significant overhaul the user interface deserves a new major version.

[The migration docs](https://www.filepicker.com/documentation/file_ingestion/javascript_api/migration?v=v2) acknowledge that the new dialog can break customized UI.

> Since dialog v2 was completely rebuilt from the ground up, custom css files from v1 will not work correctly with it.

From your point of view, why not bump the version to 2.0?

**Comment by maurogeorge** [comment]
> Somebody at Filepicker thought the changes to the API were significant enough to warrant a new major 

The filepicker-rails is not a mirror in case of versions around the Filepicker JS API, it is only a thin wrapper around the JS API. I don't know what is the release policy that Filepicker JS API uses, in the gem we use the SemVer.

I really don't know about this quote from the docs thanks to share.

What you think about lock the gem on the 1.4.0 the last one that uses the JS API V1. The 1.4.0 is the last one that will use the API V1 if we bump 2.0.0 all new features will be using only the JS API V2 we will not backport any features. I thinking locking in the 1.4.0 solves your problem right?

**Comment by monkbroc** [comment]
I made a Pull Request with my suggestion.

**Comment by Jaco-Pretorius** [comment]
:+1: For upgrading the gem version to 2.0, I don't see a reason for not matching the filepicker API versioning in this regard

**Comment by alan707** [comment]
Agreed.  +1 for upgrading gem version to 2.0

**Comment by maurogeorge** [comment]
Even that for Filepicker the:

> Since dialog v2 was completely rebuilt from the ground up, custom css files from v1 will not work correctly with it.

Is not a breaking change, I agree that is a breaking change on the semver, I really expect that my custom CSS works after a MINOR release.

So I yanked the [1.5.0 and 1.5.1](https://rubygems.org/gems/filepicker-rails) and release the [2.0.0](https://github.com/Ink/filepicker-rails/blob/master/CHANGELOG.md) with the content from 1.5.0 and 1.5.1.

@monkbroc thanks for the report and for this CSS custom problem. If it is ok for you please close this issue.

**Comment by monkbroc** [comment]
Nice discussion. Obrigado @maurogeorge

**Comment by maurogeorge** [comment]
Thanks @monkbroc :smiley:
