### ISSUE TITLE
Support for `crop_first` parameter

### ISSUE THREAD

**Issue by farnoy** [Ink/filepicker-rails#127]
It's not available [here](https://github.com/Ink/filepicker-rails/blob/ebd35123b46ee304787b131842da4e98e2a53b7c/app/helpers/filepicker_rails/application_helper.rb#L173-L175), why?

**Comment by maurogeorge** [comment]
You are right, this is not a valid option, feel free to send a PR to add this behavior.

More info about [contributing here](https://github.com/Ink/filepicker-rails/blob/master/CONTRIBUTING.md).

Thanks for the report @farnoy

**Comment by maurogeorge** [comment]
Closed via #129
