### ISSUE TITLE
filepicker_image_tag does not work with Cloudfront URLs

### ISSUE THREAD

**Issue by tarr11** [Ink/filepicker-rails#130]
It returns 403 and does not match actual URL

Following the instructions I tried to set up cloudfront CDN  (seem my [stackoverflow question here](http://stackoverflow.com/questions/31775862/how-to-get-cloudfront-url-from-filepicker-rails) )

The cloudfront URL returned does not match the actual URL.
Filepicker URL:
https://www.filepicker.io/api/file/big-long-key

Cloudfront URL:
https://mycloudfronturl.cloudfront.net/big-long-key_filename.png

Right now, the only option is to query the filepicker URL for metadata and then save it myself.  

Would suggest either deprecating the `filepicker_image_tag` for CDN urls or fixing to support the way URLs actually works

**Comment by maurogeorge** [comment]
Hi @tarr11 

Do you configured following this docs https://www.filepicker.com/documentation/cdn/ ?

As you can see here https://www.filepicker.com/documentation/cdn/use_cloudfront the path is the same changing only the domain. This is the [actual behavior](https://github.com/Ink/filepicker-rails/blob/810f44e726c0d85c9efd7375b5b08fac2f84f3f9/spec/helpers/application_helper_spec.rb#L270-L289) of the gem.

**Comment by tarr11** [comment]
I believe that test is not modelling the actual behavior of filepicker.  Posting to filepicker returns URLs in this form:
`https://www.filepicker.io/api/file/big-long-key`

Your test assumes keys of this type:
`https://www.filepicker.io/big-long-key`

**Comment by maurogeorge** [comment]
The test reflects the same behavior [described here](https://www.filepicker.com/documentation/cdn/use_cloudfront), changing only the path:

- https://www.filepicker.io/api/file/N49i6hPRBeropWnCWOLw
- https://d2nl1simbk63ds.cloudfront.net/api/file/N49i6hPRBeropWnCWOLw

This is the only thing that the gem does. I recommend you double check the CDN instructions https://www.filepicker.com/documentation/cdn/ and if the problem persist try reach the Filepicker support.

**Comment by maurogeorge** [comment]
Closing since no more feedback here.

**Comment by tarr11** [comment]
Just to follow up here, the problem is because the documentation recommends going directly from Filepicker's store to Cloudfront.  In my case, i store the files in S3, and then use Cloudfront backed by my S3 URL.  I believe this is a better design choice, since I do not have to rely on Filepicker as a primary store.  

The gem works in the case where you go from Filepicker -> Cloudfront, but does not work in the case where you go from Filepicker -> S3 -> Cloudfront.  In this case, the URLs do not have /file/api directory prefix in either S3 or cloudfront, and the filename is not the random ID generated by FIlepicker, and this is what causes the error.
