### ISSUE TITLE
changelog link to V2 migration info is not correct

### ISSUE THREAD

**Issue by jpwynn** [Ink/filepicker-rails#132]
The link in the changelog to the V2 migraiton info is incorrect, it just goes to the root docs.

**Comment by maurogeorge** [comment]
It seens that the migration page was changed. Do you know a page on the docs the show how to do the migration?

Thanks for the report

**Comment by amione** [comment]
Hi all,
Sorry for the confusion. We have been shifting some things around in our documentation. The link should work again as we have added redirects so that older links will hit the correct pages.

Regards,
Andrew Mione

**Comment by maurogeorge** [comment]
Thanks for the feedback @amione :+1:

**Comment by maurogeorge** [comment]
Closing since the links are correct now on the CHANGELOG.
